project_id = "jguylowswwgjvotdcsfj"

[functions.calculate-energy-score]
verify_jwt = false

[functions.ktrenz-data-collector]
verify_jwt = false

[functions.ktrenz-streaming-guide]
verify_jwt = false

[functions.crawl-x-mentions]
verify_jwt = false

[functions.buzz-cron]
verify_jwt = false
