import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const koreanNames: Record<string, string> = {
  "(G)I-DLE": "(여자)아이들",
  "AB6IX": "에이비식스",
  "aespa": "에스파",
  "All Day Project": "올데이프로젝트",
  "ASTRO": "아스트로",
  "ATEEZ": "에이티즈",
  "Babymonster": "베이비몬스터",
  "BIGBANG": "빅뱅",
  "Binnie": "비니",
  "BLACKPINK": "블랙핑크",
  "Block B": "블락비",
  "Bobby": "바비",
  "BOYNEXTDOOR": "보이넥스트도어",
  "Brown Eyed Girls": "브라운아이드걸스",
  "BTS": "방탄소년단",
  "BTS J-Hope": "제이홉",
  "BTS Jungkook": "정국",
  "BTS V": "뷔",
  "Chenle": "천러",
  "CIX": "씨아이엑스",
  "CLC": "씨엘씨",
  "CNBLUE": "씨엔블루",
  "CRAVITY": "크래비티",
  "DPR LIVE": "디피알라이브",
  "Dreamcatcher": "드림캐쳐",
  "ENHYPEN": "엔하이픈",
  "EPEX": "이펙스",
  "EPIK HIGH": "에픽하이",
  "Eunhyuk": "은혁",
  "EVERGLOW": "에버글로우",
  "Evnne": "이븐",
  "EXID": "이엑스아이디",
  "EXO": "엑소",
  "GD": "지드래곤",
  "Girl Crush": "걸크러쉬",
  "Girls Generation": "소녀시대",
  "Gong Seung Yeon": "공승연",
  "Gugudan": "구구단",
  "GWSN": "공원소녀",
  "H1GHR MUSIC": "하이어뮤직",
  "Hello Venus": "헬로비너스",
  "Highlight": "하이라이트",
  "Hoshi": "호시",
  "Hwa Sa": "화사",
  "Hwasa": "화사",
  "Hyoyeon": "효연",
  "iKON": "아이콘",
  "IU": "아이유",
  "Ive": "아이브",
  "Joshua": "조슈아",
  "Joy": "조이",
  "Jun": "준",
  "Kang Daniel": "강다니엘",
  "Kep1er": "케플러",
  "KISS OF LIFE": "키스오브라이프",
  "Loco": "로꼬",
  "LOONA": "이달의소녀",
  "MAMAMOO": "마마무",
  "Mina": "미나",
  "Mingyu": "민규",
  "MONSTA X": "몬스타엑스",
  "Monsta X": "몬스타엑스",
  "Nayeon": "나연",
  "NCT": "엔시티",
  "NCT 127": "엔시티 127",
  "NCT Dream": "엔시티 드림",
  "NewJeans": "뉴진스",
  "NMIXX": "엔믹스",
  "OH MY GIRL": "오마이걸",
  "ONEUS": "원어스",
  "P1Harmony": "피원하모니",
  "PLAVE": "플레이브",
  "Red Velvet": "레드벨벳",
  "RIIZE": "라이즈",
  "SEVENTEEN": "세븐틴",
  "SHINee": "샤이니",
  "STAYC": "스테이씨",
  "Stray Kids": "스트레이키즈",
  "Sunmi": "선미",
  "Super Junior": "슈퍼주니어",
  "TEMPEST": "템페스트",
  "The Boyz": "더보이즈",
  "TOMORROW X TOGETHER (TXT)": "투모로우바이투게더",
  "TREASURE": "트레저",
  "tripleS": "트리플에스",
  "TWS": "투어스",
  "TXT": "투모로우바이투게더",
  "TWICE": "트와이스",
  "VIXX": "빅스",
  "WayV": "웨이브이",
  "WINNER": "위너",
  "Wonder Girls": "원더걸스",
  "Woo!ah!": "우아",
  "XG": "엑스지",
  "Xdinary Heroes": "엑스디너리히어로즈",
  "ZEROBASEONE": "제로베이스원",
  "ZB1": "제로베이스원",
  "LE SSERAFIM": "르세라핌",
  "ILLIT": "아일릿",
  "Kang Seung Yoon": "강승윤",
  "KEY": "키",
  "Lay Zhang": "레이",
  "Lisa": "리사",
  "Mark": "마크",
  "Miyeon": "미연",
  "N.Flying": "엔플라잉",
  "Pentagon": "펜타곤",
  "PURPLE KISS": "퍼플키스",
  "Rosé": "로제",
  "Seulgi": "슬기",
  "Solar": "솔라",
  "Somi": "소미",
  "Taeyeon": "태연",
  "Taemin": "태민",
  "Wendy": "웬디",
  "Wheein": "휘인",
  "Yeonjun": "연준",
  "Yeji": "예지",
  "Yuna": "유나",
  "Yuri": "유리",
  "Bae": "배",
  "Bae Bae": "배배",
  "C-REAL": "씨리얼",
  "Cortis": "코르티스",
  "D1CE": "디원스",
  "H.O.T": "H.O.T",
  "High4": "하이포",
  "HNB": "HNB",
  "In-yeop": "인엽",
  "Jung Hyung Don": "정형돈",
  "JYJ": "JYJ",
  "KARD": "카드",
  "Kim Woo Seok": "김우석",
  "Kwon Eun-bi": "권은비",
  "L": "엘",
  "Lee Hi": "이하이",
  "Lovelyz": "러블리즈",
  "LUMINOUS": "루미너스",
  "Mimi": "미미",
  "Minho": "민호",
  "Minju": "민주",
  "Minnie": "민니",
  "Momo": "모모",
  "Moonbyul": "문별",
  "N.O.M": "N.O.M",
  "N.Sonic": "엔소닉",
  "NATURE": "네이처",
  "NCT 2022": "엔시티 2022",
  "NiziU": "니쥬",
  "Noh Hongchul": "노홍철",
  "ONF": "온앤오프",
  "Orange Caramel": "오렌지캬라멜",
  "pH-1": "pH-1",
  "PRISTIN": "프리스틴",
  "Renjun": "런쥔",
  "Rocket Punch": "로켓펀치",
  "Sejeong": "세정",
  "Seungkwan": "승관",
  "Seungmin": "승민",
  "Seungri": "승리",
  "Shin Dongwoo": "신동우",
  "Shuhua": "슈화",
  "SinB": "신비",
  "Siwon": "시원",
  "SIXBOMB": "식스밤",
  "SNSD": "소녀시대",
  "Sohee": "소희",
  "Soyeon": "소연",
  "Sunggyu": "성규",
  "Sungmin": "성민",
  "Sunny": "써니",
  "Ten": "텐",
  "TST": "일급비밀",
  "TVXQ": "동방신기",
  "Wanna One": "워너원",
  "Winwin": "윈윈",
  "Wonpil": "원필",
  "WOO!AH!": "우아",
  "Woohyun": "우현",
  "Xikers": "싸이커스",
  "Yeonhee": "연희",
  "Yeosang": "여상",
  "Yerin": "예린",
  "Yuju": "유주",
  "Zero Base One": "제로베이스원",
  "A.S.O": "A.S.O",
  "B.O.I": "B.O.I",
  "FNC": "FNC",
  "K-Trendz Supporters": "케이트렌즈 서포터즈",
  "Rising Star": "라이징스타",
  "Rockets": "로케츠",
  "SINGER": "싱어",
  "TROUBLE": "트러블",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Get all artists without name_ko
    const { data: artists, error: fetchErr } = await supabase
      .from("v3_artist_tiers")
      .select("id, display_name")
      .is("name_ko", null);

    if (fetchErr) throw fetchErr;

    let updated = 0;
    for (const artist of artists || []) {
      const ko = koreanNames[artist.display_name];
      if (ko) {
        const { error } = await supabase
          .from("v3_artist_tiers")
          .update({ name_ko: ko })
          .eq("id", artist.id);
        if (!error) updated++;
      }
    }

    return new Response(JSON.stringify({ updated, total: artists?.length }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
