
-- KST 05:05 = UTC 20:05 시작
-- YouTube (4): UTC 20:05-20:08
SELECT cron.schedule('ktrenz-youtube-batch-0', '5 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"youtube","batchIndex":0,"batchSize":15}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-youtube-batch-1', '6 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"youtube","batchIndex":1,"batchSize":15}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-youtube-batch-2', '7 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"youtube","batchIndex":2,"batchSize":15}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-youtube-batch-3', '8 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"youtube","batchIndex":3,"batchSize":15}'::jsonb) AS request_id;$$);

-- Music (10): UTC 20:10-20:19
SELECT cron.schedule('ktrenz-music-batch-0', '10 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":0,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-1', '11 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":1,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-2', '12 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":2,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-3', '13 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":3,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-4', '14 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":4,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-5', '15 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":5,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-6', '16 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":6,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-7', '17 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":7,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-8', '18 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":8,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-music-batch-9', '19 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"music","batchIndex":9,"batchSize":6}'::jsonb) AS request_id;$$);

-- Hanteo: UTC 20:20
SELECT cron.schedule('ktrenz-hanteo', '20 20 * * *', $$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/ktrenz-data-collector', headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb, body:='{"source":"hanteo"}'::jsonb) AS request_id;$$);

-- Buzz (50): UTC 20:25~21:14
SELECT cron.schedule('ktrenz-buzz-batch-0','25 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":0}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-1','26 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":1}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-2','27 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":2}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-3','28 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":3}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-4','29 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":4}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-5','30 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":5}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-6','31 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-7','32 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":7}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-8','33 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":8}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-9','34 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":9}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-10','35 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":10}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-11','36 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":11}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-12','37 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":12}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-13','38 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":13}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-14','39 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":14}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-15','40 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":15}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-16','41 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":16}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-17','42 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":17}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-18','43 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":18}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-19','44 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":19}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-20','45 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":20}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-21','46 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":21}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-22','47 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":22}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-23','48 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":23}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-24','49 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":24}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-25','50 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":25}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-26','51 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":26}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-27','52 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":27}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-28','53 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":28}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-29','54 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":29}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-30','55 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":30}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-31','56 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":31}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-32','57 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":32}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-33','58 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":33}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-34','59 20 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":34}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-35','0 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":35}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-36','1 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":36}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-37','2 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":37}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-38','3 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":38}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-39','4 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":39}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-40','5 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":40}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-41','6 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":41}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-42','7 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":42}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-43','8 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":43}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-44','9 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":44}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-45','10 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":45}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-46','11 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":46}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-47','12 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":47}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-48','13 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":48}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-buzz-batch-49','14 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/buzz-cron',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchSize":1,"batchOffset":49}'::jsonb) AS request_id;$$);

-- Energy (20): UTC 21:20~21:39
SELECT cron.schedule('ktrenz-energy-batch-0','20 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":0,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-1','21 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":1,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-2','22 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":2,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-3','23 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":3,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-4','24 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":4,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-5','25 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":5,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-6','26 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":6,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-7','27 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":7,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-8','28 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":8,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-9','29 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":9,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-10','30 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":10,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-11','31 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":11,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-12','32 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":12,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-13','33 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":13,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-14','34 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":14,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-15','35 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":15,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-16','36 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":16,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-17','37 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":17,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-18','38 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":18,"batchSize":6}'::jsonb) AS request_id;$$);
SELECT cron.schedule('ktrenz-energy-batch-19','39 21 * * *',$$SELECT net.http_post(url:='https://jguylowswwgjvotdcsfj.supabase.co/functions/v1/calculate-energy-score',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndXlsb3dzd3dnanZvdGRjc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTY5MzQsImV4cCI6MjA3NzQ3MjkzNH0.WYZndHJtDXwFITy9FYKv7bhqDcmhqNwZNrj_gEobJiM"}'::jsonb,body:='{"batchIndex":19,"batchSize":6}'::jsonb) AS request_id;$$);
